package com.dektar.pi.piswitch;

import android.app.PendingIntent;
import android.appwidget.AppWidgetManager;
import android.appwidget.AppWidgetProvider;
import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.widget.RemoteViews;

/**
 * AppWidgetProvider for PiSwitch
 */
public class PiSwitchWidgetProvider extends AppWidgetProvider {

    private static final String HAS_NO_DATA_KEY = "no_data";
    private static final String IS_ON_KEY = "is_on";
    private static final String BUTTON_PUSHED_KEY = "button_pushed";

    private boolean mIsOn = false;
    private boolean mHasNoData = true;
    private boolean mButtonClicked = true;
    private PiController mPiController;

    @Override
    public void onUpdate(final Context context, AppWidgetManager appWidgetManager, int[] appWidgetIds) {
        Log.d("onUpdate", "received intent");
        final int size = appWidgetIds.length;

        for (int i = 0; i < size; i++) {
            int widgetId = appWidgetIds[i];

            RemoteViews remoteViews = new RemoteViews(context.getPackageName(),
                    R.layout.app_widget);
            if (mButtonClicked) {
                // The button was just clicked. Start the request for toggle & status.
                setRemoteViewsPending(context, remoteViews);
                final Intent updateIntent = new Intent(context, PiSwitchWidgetProvider.class);
                updateIntent.setAction(AppWidgetManager.ACTION_APPWIDGET_UPDATE);
                updateIntent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, appWidgetIds);
                updateIntent.putExtra(BUTTON_PUSHED_KEY, false); // autogenerated intent
                if (mPiController == null) {
                     mPiController =
                            new PiController(context, new PiController.OnPiStatusResponseListener() {
                                @Override
                                public void onStatus(boolean isOn) {
                                    updateIntent.putExtra(IS_ON_KEY, isOn);
                                    updateIntent.putExtra(HAS_NO_DATA_KEY, false);
                                    context.sendBroadcast(updateIntent);
                                }

                                @Override
                                public void onError() {
                                    updateIntent.putExtra(HAS_NO_DATA_KEY, true);
                                    context.sendBroadcast(updateIntent);
                                }
                            });
                } else {
                    mPiController.refreshOptions(context);
                }
                mPiController.toggle(!mIsOn);
            } else {
                // This is an update from a status request. Reset the button click intent.
                if (mHasNoData) {
                    setRemoteViewsPending(context, remoteViews);
                } else {
                    setRemoteViewsUi(mIsOn, context, remoteViews);
                }
                Intent clickIntent = new Intent(context, PiSwitchWidgetProvider.class);
                clickIntent.setAction(AppWidgetManager.ACTION_APPWIDGET_UPDATE);
                clickIntent.putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, appWidgetIds);
                clickIntent.putExtra(BUTTON_PUSHED_KEY, true); // button push intent
                clickIntent.putExtra(IS_ON_KEY, mIsOn);
                PendingIntent pendingIntent = PendingIntent.getBroadcast(context,
                        0, clickIntent, PendingIntent.FLAG_UPDATE_CURRENT);

                remoteViews.setOnClickPendingIntent(R.id.widget_toggle_button, pendingIntent);
            }
            appWidgetManager.updateAppWidget(widgetId, remoteViews);
        }
    }

    private void setRemoteViewsPending(Context context, RemoteViews remoteViews) {
        remoteViews.setTextViewText(R.id.widget_toggle_button,
                context.getResources().getString(R.string.button_text_loading));
        remoteViews.setTextColor(R.id.widget_toggle_button,
                context.getResources().getColor(R.color.button_color_loading));
    }

    private void setRemoteViewsUi(boolean isOn, Context context, RemoteViews remoteViews) {
        if (isOn) {
            remoteViews.setTextViewText(R.id.widget_toggle_button,
                    context.getResources().getString(R.string.button_text_turn_off));
            remoteViews.setTextColor(R.id.widget_toggle_button,
                    context.getResources().getColor(R.color.button_color_turn_off));
        } else {
            remoteViews.setTextViewText(R.id.widget_toggle_button,
                    context.getResources().getString(R.string.button_text_turn_on));
            remoteViews.setTextColor(R.id.widget_toggle_button,
                    context.getResources().getColor(R.color.button_color_turn_on));
        }
    }

    @Override
    public void onReceive(final Context context, Intent intent) {
        Log.d("onReceive", "received intent");
        mButtonClicked = intent.getBooleanExtra(BUTTON_PUSHED_KEY, mButtonClicked);
        mHasNoData = intent.getBooleanExtra(HAS_NO_DATA_KEY, mHasNoData);
        mIsOn = intent.getBooleanExtra(IS_ON_KEY, mIsOn);
        super.onReceive(context, intent);
    }
}
